version: '3.8'

services:
  webserver:
    container_name: test-ws
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 8086:80
  db:
    container_name: test-db
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=ke1nes
      - MYSQL_PASSWORD=ke1nes
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=example_db
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    container_name: test-adminer
    depends_on:
      - db
    image: adminer
    ports:
      - 8033:8080
  